apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f freeipa.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f freeipa.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: client
    spec:
      containers:
        - image: client
          name: client
          ports:
            - containerPort: 22
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: client-claim0
            - mountPath: /sys/fs/cgroup
              name: client-claim1
              readOnly: true
      hostname: client
      restartPolicy: Always
      subdomain: example.test
      volumes:
        - name: client-claim0
          persistentVolumeClaim:
            claimName: client-claim0
        - name: client-claim1
          persistentVolumeClaim:
            claimName: client-claim1
            readOnly: true
status: {}
